#### **CORRECTITUD DE DATOS**

In [228]:
import pandas as pd 
import numpy as np

catalogo_productos = pd.read_csv("Datos-finales/catalogo_productos.csv")
especificaciones_cajas = pd.read_csv("Datos-finales/especificaciones_cajas.csv")
operaciones_planta = pd.read_csv("Datos-finales/operaciones_planta.csv")
procurement_cajas = pd.read_csv("Datos-finales/procurement_cajas.csv")

Creamos una función que nos permita verificar la correctitud de los datos. La idea es calcular manualmente las filas de una columna específica y luego compararla con las de la existente.

In [229]:
def verificar_correctitud(df, col1, col2):
    df = df.copy()
    df['coincide'] = np.isclose(df[col1], df[col2])
    
    # Filtrar las que no coinciden
    no_coinciden = df[df['coincide'] == False]
    
    if no_coinciden.empty:
        print("TODAS LAS FILAS COINCIDEN.")
        return None
    else:
        print(f"{len(no_coinciden)} FILAS NO coinciden")
        return no_coinciden[[col1, col2, 'coincide']]

In [230]:
especificaciones_cajas['caja_exterior_largo_calculado'] = (
    especificaciones_cajas['caja_interior_largo'] + 
    2 * especificaciones_cajas['caja_grosor_mm']
)

especificaciones_cajas['caja_exterior_ancho_calculado'] = (
    especificaciones_cajas['caja_interior_ancho'] + 
    2 * especificaciones_cajas['caja_grosor_mm']
)

especificaciones_cajas['caja_exterior_alto_calculado'] = (
    especificaciones_cajas['caja_interior_alto'] + 
    2 * especificaciones_cajas['caja_grosor_mm']
)

verificar_correctitud(especificaciones_cajas, 'caja_exterior_largo', 
                                'caja_exterior_largo_calculado')

print("-" * 30)
verificar_correctitud(especificaciones_cajas, 'caja_exterior_ancho', 
                                'caja_exterior_ancho_calculado')
print("-" * 30)
verificar_correctitud(especificaciones_cajas, 'caja_exterior_alto', 
                                'caja_exterior_alto_calculado')

TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.

In [231]:
operaciones_planta['volumen_producto_total_calculado'] = (
    operaciones_planta['volumen_producto_canal_servicios_comida'] +
    operaciones_planta['volumen_producto_canal_minorista'] +
    operaciones_planta['volumen_producto_canal_cadenas_corporativas'] +
    operaciones_planta['volumen_producto_canal_otros']
)

verificar_correctitud(operaciones_planta, 'volumen_producto_total', 
                                'volumen_producto_total_calculado')

TODAS LAS FILAS COINCIDEN.

In [232]:
operaciones_planta['volumen_producto_total_calculado2'] = (
    operaciones_planta['volumen_producto_planta_buenos_aires'] +
    operaciones_planta['volumen_producto_planta_curitiba'] +
    operaciones_planta['volumen_producto_planta_santiago'] +
    operaciones_planta['volumen_producto_planta_monterrey'] +
    operaciones_planta['volumen_producto_planta_bakersfield']
)

verificar_correctitud(operaciones_planta, 'volumen_producto_total', 
                                'volumen_producto_total_calculado2')

TODAS LAS FILAS COINCIDEN.

In [233]:
operaciones_planta['cantidad_pallets_total_calculado'] = (
    operaciones_planta['cantidad_pallets_planta_buenos_aires'] +
    operaciones_planta['cantidad_pallets_planta_curitiba'] +
    operaciones_planta['cantidad_pallets_planta_santiago'] +
    operaciones_planta['cantidad_pallets_planta_monterrey'] +
    operaciones_planta['cantidad_pallets_planta_bakersfield']
)

verificar_correctitud(operaciones_planta, 'cantidad_pallets_total',
                                'cantidad_pallets_total_calculado')

TODAS LAS FILAS COINCIDEN.

In [234]:
operaciones_planta['costo_pallets_total_calculado'] = (
    operaciones_planta['costo_pallets_planta_buenos_aires'] +
    operaciones_planta['costo_pallets_planta_curitiba'] +
    operaciones_planta['costo_pallets_planta_santiago'] +
    operaciones_planta['costo_pallets_planta_monterrey'] +
    operaciones_planta['costo_pallets_planta_bakersfield']
)

verificar_correctitud(operaciones_planta, 'costo_pallets_total',
                                'costo_pallets_total_calculado')

TODAS LAS FILAS COINCIDEN.

In [235]:
operaciones_planta['costo_total_calculado'] = (
    operaciones_planta['costo_total_planta_buenos_aires'] +
    operaciones_planta['costo_total_planta_curitiba'] +
    operaciones_planta['costo_total_planta_santiago'] +
    operaciones_planta['costo_total_planta_monterrey'] +
    operaciones_planta['costo_total_planta_bakersfield']
)

verificar_correctitud(operaciones_planta, 'costo_total',
                                'costo_total_calculado')

TODAS LAS FILAS COINCIDEN.

In [236]:
operaciones_planta['costo_pallets_planta_buenos_aires_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_buenos_aires']
) 

operaciones_planta['costo_pallets_planta_curitiba_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_curitiba']
) 

operaciones_planta['costo_pallets_planta_santiago_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_santiago']
) 

operaciones_planta['costo_pallets_planta_monterrey_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_monterrey']
) 

operaciones_planta['costo_pallets_planta_bakersfield_calculado'] = (
    150 * operaciones_planta['cantidad_pallets_planta_bakersfield']
) 

verificar_correctitud(operaciones_planta, 'costo_pallets_planta_buenos_aires',
                                'costo_pallets_planta_buenos_aires_calculado')
print("-" * 30)
verificar_correctitud(operaciones_planta, 'costo_pallets_planta_curitiba',
                                'costo_pallets_planta_curitiba_calculado')
print("-" * 30)
verificar_correctitud(operaciones_planta, 'costo_pallets_planta_santiago',
                                'costo_pallets_planta_santiago_calculado')
print("-" * 30)
verificar_correctitud(operaciones_planta, 'costo_pallets_planta_monterrey',
                                'costo_pallets_planta_monterrey_calculado')
print("-" * 30)
verificar_correctitud(operaciones_planta, 'costo_pallets_planta_bakersfield',
                                'costo_pallets_planta_bakersfield_calculado')

TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.
------------------------------
TODAS LAS FILAS COINCIDEN.

In [237]:
# Hacemos un merge de la tabla de producto con la de caja
df_merge = catalogo_productos.merge(
    operaciones_planta,
    on='codigo_producto'  # hacemos un join por la clave de caja
)

df_merge = df_merge.merge(
    procurement_cajas,
    on='caja_tipo_id',  # hacemos un join por la clave de caja
    how='left'          # dos productos distintos pueden usar la misma caja
)

In [238]:
df_merge['costo_total_planta_buenos_aires_calculado'] = (
    df_merge['volumen_producto_planta_buenos_aires'] *
    df_merge['costo_unitario_planta_buenos_aires']
)

verificar_correctitud(df_merge, 'costo_total_planta_buenos_aires',
                                'costo_total_planta_buenos_aires_calculado')

63 FILAS NO coinciden

,costo_total_planta_buenos_aires,costo_total_planta_buenos_aires_calculado,coincide
7,9222.570,8197.84,False
19,41172.300,36597.60,False
20,22503.040,19690.16,False
21,9585.550,7668.44,False
26,46081.840,40321.61,False
...,...,...,...
394,11520.900,10240.80,False
400,10630.980,9449.76,False
424,8780.200,7024.16,False
425,5454.020,4958.20,False
426,25.025,22.75,False

In [239]:
df_merge['costo_total_planta_curitiba_calculado'] = (
    df_merge['volumen_producto_planta_curitiba'] *
    df_merge['costo_unitario_planta_curitiba']
)

verificar_correctitud(df_merge, 'costo_total_planta_curitiba',
                                'costo_total_planta_curitiba_calculado')

95 FILAS NO coinciden

,costo_total_planta_curitiba,costo_total_planta_curitiba_calculado,coincide
1,72389.720,63341.005,False
6,27405.495,24360.440,False
12,79691.040,69729.660,False
16,68535.480,59968.545,False
22,8698.410,7731.920,False
...,...,...,...
438,251862.520,220379.705,False
439,39882.080,34896.820,False
442,4745.520,4218.240,False
453,508.410,451.920,False
461,12598.040,11023.285,False

In [240]:
df_merge['costo_total_planta_santiago_calculado'] = (
    df_merge['volumen_producto_planta_santiago'] *
    df_merge['costo_unitario_planta_santiago']
)

verificar_correctitud(df_merge, 'costo_total_planta_santiago',
                                'costo_total_planta_santiago_calculado')

94 FILAS NO coinciden

,costo_total_planta_santiago,costo_total_planta_santiago_calculado,coincide
0,18608.10,16747.29,False
8,3228.61,2935.10,False
36,38691.90,34392.80,False
67,28097.30,22477.84,False
75,5242.90,4194.32,False
...,...,...,...
455,40.04,36.40,False
456,29.68,25.97,False
457,38.50,35.00,False
458,2125.97,1932.70,False
459,3035.34,2759.40,False

In [241]:
df_merge['costo_total_planta_monterrey_calculado'] = (
    df_merge['volumen_producto_planta_monterrey'] *
    df_merge['costo_unitario_planta_monterrey']
)

verificar_correctitud(df_merge, 'costo_total_planta_monterrey',
                                'costo_total_planta_monterrey_calculado')

37 FILAS NO coinciden

,costo_total_planta_monterrey,costo_total_planta_monterrey_calculado,coincide
0,55618.920,49439.040,False
8,1182.720,1034.880,False
24,53658.640,46951.310,False
25,28646.800,22917.440,False
68,24923.925,22154.600,False
75,2905.045,2376.855,False
89,33503.400,29780.800,False
90,24542.000,22087.800,False
92,57198.960,44488.080,False
93,45363.955,58325.085,False
104,36033.200,31529.050,False
184,1562.275,1278.225,False
185,230.945,188.955,False
186,5729.750,5156.775,False
188,2902.900,2375.100,False
189,2715.570,2221.830,False
287,37694.720,32982.880,False
291,89306.560,78143.240,False
292,30655.800,24524.640,False
327,11547.900,10393.110,False
333,7055.620,6414.200,False
334,7807.800,7098.000,False
337,4291.950,3862.755,False
338,4315.350,3883.815,False
339,7569.250,6812.325,False
345,12382.370,11256.700,False
350,156618.000,137040.750,False
423,19635.200,15708.160,False
424,1903.850,1523.080,False
425,7513.155,6678.360,False
426,15.210,13.520,False
446,14.000,12.250,False
447,15.750,14.000,False
449,16.380,14.560,False
455,15.120,13.230,False
457,14.000,12.250,False
460,28145.000,25330.500,False

In [242]:
df_merge['costo_total_planta_bakersfield_calculado'] = (
    df_merge['volumen_producto_planta_bakersfield'] *
    df_merge['costo_unitario_planta_bakersfield']
)

verificar_correctitud(df_merge, 'costo_total_planta_bakersfield',
                                'costo_total_planta_bakersfield_calculado')

50 FILAS NO coinciden

,costo_total_planta_bakersfield,costo_total_planta_bakersfield_calculado,coincide
2,96603.360,84527.940,False
3,141291.800,123630.325,False
8,1920.380,1745.800,False
11,157850.000,138118.750,False
17,101679.760,88969.790,False
64,53924.640,47184.060,False
72,16147.040,14128.660,False
75,3430.570,2494.960,False
136,32452.550,25962.040,False
184,1844.700,1341.600,False
185,272.415,198.120,False
186,6767.150,6090.435,False
188,3428.425,2493.400,False
189,3207.490,2332.720,False
203,59083.920,52519.040,False
204,45924.320,40183.780,False
205,43151.680,37757.720,False
206,45924.320,40183.780,False
207,43151.680,37757.720,False
226,1451.520,1270.080,False
227,2161.390,1375.430,False
228,1451.520,1995.840,False
230,34193.040,29918.910,False
231,26649.280,23318.120,False
316,41263.740,36678.880,False
319,21906.560,19168.240,False
327,13638.300,12274.470,False
333,8332.610,7575.100,False
334,9220.640,8382.400,False
337,5068.700,4561.830,False
338,5096.650,4586.985,False
339,8939.450,8045.505,False
340,245042.000,214411.750,False
341,238938.560,209071.240,False
353,37285.920,33143.040,False
379,59921.680,52431.470,False
380,59012.800,51636.200,False
381,59921.680,52431.470,False
382,59012.800,51636.200,False
388,213760.960,187040.840,False
408,32143.860,28572.320,False
411,52811.720,46210.255,False
415,11437.140,9357.660,False
416,134958.880,118089.020,False
442,9329.320,8481.200,False
443,12484.780,11349.800,False
446,23.100,21.000,False
454,1127.840,986.860,False
455,23.870,21.700,False
457,23.100,21.000,False

In [243]:
df_merge

,codigo_producto,descripcion_producto,ingrediente_forma,tipo_proyecto,subcategoria,categoria,tamaño_corte,peso_neto_caja,tamaño_paquete,cantidad_paquetes,...,descuento_planta_buenos_aires_original,descuento_planta_curitiba_original,descuento_planta_santiago_original,descuento_planta_monterrey_original,descuento_planta_bakersfield_original,costo_total_planta_buenos_aires_calculado,costo_total_planta_curitiba_calculado,costo_total_planta_santiago_calculado,costo_total_planta_monterrey_calculado,costo_total_planta_bakersfield_calculado
0,BR0001,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Reserva Privada,Bastones clasicos,Fino,12.50,"5 X 2,5 KG",5,...,+10%,-30%,+0%,-10%,+10%,0.0,701555.540,16747.29,49439.040,0.000
1,BR0002,Espirales de brocoli - clasico - Caja de 13 pa...,Espirales de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,9.75,"13 X 0,75 KG",13,...,+10%,-20%,-30%,+10%,+0%,0.0,63341.005,0.00,0.000,0.000
2,BR0003,Gajos de brocoli - sazonado - Caja de 13 packs...,Gajos de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,9.75,"13 X 0,75 KG",13,...,"+10,00%",-10%,+10%,10,-20%,0.0,0.000,0.00,0.000,84527.940
3,BR0004,Bastones rectos de brocoli - crocante - Caja d...,Bastones rectos de brocoli,Estacional,Bastones clasicos - Sigilo,Bastones clasicos,Grueso,11.25,"9 X 1,5 KG",9,...,+10%,-20%,+10%,+10%,-20%,0.0,0.000,0.00,0.000,123630.325
4,BR0005,"13 bolsas de 0,75 kg | Espirales de brocoli si...",Espirales de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,9.75,"13 X 0,75 KG",13,...,+10%,-20,-30,+10%,+10%,0.0,4248.160,0.00,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
458,BR0417,Mix crujiente de brocoli - clasico - Caja de 1...,Mix crujiente de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,8.25,"11 X 0,75 KG",11,...,+ 10%,+10%,+10%,+10%,10%,0.0,0.000,1932.70,0.000,0.000
459,BR0418,"BonsaiGreen Mix crujiente de brocoli 11 x 0,75 kg",Mix crujiente de brocoli,Forma estable,Bastones clasicos - Sigilo,Bastones clasicos,Forma,8.25,"11 X 0,75 KG",11,...,+ 10%,+10%,+10%,+10%,10%,0.0,0.000,2759.40,0.000,0.000
460,BR0419,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Reserva Privada,Bastones clasicos,Corte steak,12.50,"5 X 2,5 KG",5,...,+10%,+10%,+10%,+0%,+10%,0.0,0.000,0.00,25330.500,0.000
461,BR0420,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Reserva Privada,Bastones clasicos,Medio,12.50,"5 X2,5 KG",5,...,-10%,-20%,+10%,-30%,+10%,0.0,11023.285,0.00,82639.375,0.000
462,BR0421,"5 bolsas de 2,5 kg | Bastones rectos de brocol...",Bastones rectos de brocoli,Estacional,Bastones clasicos - Reserva Privada,Bastones clasicos,Medio,12.50,"5 X 2,5 KG",5,...,+10%,-30%,-20%,-30%,-30%,0.0,0.000,0.00,66340.365,0.000