#### **REDIMENSIONAMIENTO DE LAS CAJAS**

In [54]:
import pandas as pd 
import matplotlib.pyplot as plt
from importlib import reload

import Clases.caja as caja_module
reload(caja_module)
from Clases.caja import Caja

import Clases.producto as producto_module
reload(producto_module)
from Clases.producto import Producto

especificaciones_cajas = pd.read_csv("Datos-finales/especificaciones_cajas.csv")
procurement_cajas = pd.read_csv("Datos-finales/procurement_cajas.csv")

Importamos en una lista los tipos de cajas del dataset.

In [55]:
caja_compras_merge = especificaciones_cajas.merge(procurement_cajas,
                                                  on="caja_tipo_id")

cajas = [
    Caja(
        caja_id = row["caja_tipo_id"],
        dim_interior_ancho = row["caja_interior_ancho"],
        dim_interior_largo = row["caja_interior_largo"],
        dim_interior_alto = row["caja_interior_alto"]
    )
    for _, row in caja_compras_merge.iterrows()
]

#### **Redimensionamiento con grosor = 5mm**

Para encontrar una cantidad óptima de cajas que entran en un pallet, necesitamos definir un redimensionamiento óptimo para las dimensiones internas de las cajas. Recordemos que, siguiendo el enunciado, sólo podemos redimensionar un ±10% de las dimensiones internas originales. 

Importaremos directamente los métodos de la class Caja definida previamente

In [56]:
for caja in cajas:
    caja.elegir_grosor(grosor_mm=5)
    
combinaciones_ordenadas_por_caja_5mm = {}

for caja in cajas:
    combinaciones_ordenadas = caja.redimensionamientos_posibles()
    combinaciones_ordenadas_por_caja_5mm[caja] = combinaciones_ordenadas

Exportamos en csv todas las combinaciones posibles de redimensionamiento por tipo de caja.

In [57]:
data = []

for caja, combinaciones in combinaciones_ordenadas_por_caja_5mm.items():
    for combinacion in combinaciones:
        data.append({
            'caja_id': caja.caja_id,
            'alto': combinacion['alto'],
            'ancho': combinacion['ancho'],
            'largo': combinacion['largo'],
            'utilizacion': combinacion['utilizacion_pallet'],
            'cantidad_cajas_pallet': combinacion['cantidad_cajas_pallet']
        })

df_todas_combinaciones_5mm = pd.DataFrame(data)
df_todas_combinaciones_5mm.to_csv('Redimensionamientos/redimensionamientos_5mm.csv', index=False)
df_todas_combinaciones_5mm

,caja_id,alto,ancho,largo,utilizacion,cantidad_cajas_pallet
0,02cf77de65b70dd77905e2e33d78478f,320.1,266.4,355.5,0.771946,40.0
1,02cf77de65b70dd77905e2e33d78478f,261.9,266.4,355.5,0.763013,48.0
2,02cf77de65b70dd77905e2e33d78478f,291.0,266.4,355.5,0.703895,40.0
3,02cf77de65b70dd77905e2e33d78478f,320.1,325.6,355.5,0.702963,30.0
4,02cf77de65b70dd77905e2e33d78478f,261.9,325.6,355.5,0.694828,36.0
...,...,...,...,...,...,...
5503,fea00d6f87d3f80808e9e8d1b501120a,202.4,296.0,434.5,0.401250,24.0
5504,fea00d6f87d3f80808e9e8d1b501120a,202.4,325.6,395.0,0.400958,24.0
5505,fea00d6f87d3f80808e9e8d1b501120a,165.6,296.0,395.0,0.377814,30.0
5506,fea00d6f87d3f80808e9e8d1b501120a,184.0,296.0,395.0,0.375663,27.0
5507,fea00d6f87d3f80808e9e8d1b501120a,202.4,296.0,395.0,0.365594,24.0

#### **Redimensionamiento con grosor = 4.5mm**

Repetimos lo anterior con un grosor de 4.5mm.

In [58]:
for caja in cajas:
    caja.elegir_grosor(grosor_mm=4.5)
    
combinaciones_ordenadas_por_caja_4p5mm = {}

for caja in cajas:
    combinaciones_ordenadas = caja.redimensionamientos_posibles()
    combinaciones_ordenadas_por_caja_4p5mm[caja] = combinaciones_ordenadas

In [59]:
data = []

for caja, combinaciones in combinaciones_ordenadas_por_caja_4p5mm.items():
    for combinacion in combinaciones:
        data.append({
            'caja_id': caja.caja_id,
            'alto': combinacion['alto'],
            'ancho': combinacion['ancho'],
            'largo': combinacion['largo'],
            'utilizacion': combinacion['utilizacion_pallet'],
            'cantidad_cajas_pallet': combinacion['cantidad_cajas_pallet']
        })

df_todas_combinaciones_4p5mm = pd.DataFrame(data)
df_todas_combinaciones_4p5mm.to_csv('Redimensionamientos/redimensionamientos_4.5mm.csv', index=False)
df_todas_combinaciones_4p5mm

,caja_id,alto,ancho,largo,utilizacion,cantidad_cajas_pallet
0,02cf77de65b70dd77905e2e33d78478f,291.0,266.4,355.5,0.836527,48.0
1,02cf77de65b70dd77905e2e33d78478f,320.1,266.4,355.5,0.764726,40.0
2,02cf77de65b70dd77905e2e33d78478f,291.0,325.6,355.5,0.762261,36.0
3,02cf77de65b70dd77905e2e33d78478f,261.9,266.4,355.5,0.755384,48.0
4,02cf77de65b70dd77905e2e33d78478f,320.1,325.6,355.5,0.696833,30.0
...,...,...,...,...,...,...
5503,fea00d6f87d3f80808e9e8d1b501120a,202.4,296.0,434.5,0.397160,24.0
5504,fea00d6f87d3f80808e9e8d1b501120a,202.4,325.6,395.0,0.396899,24.0
5505,fea00d6f87d3f80808e9e8d1b501120a,165.6,296.0,395.0,0.373511,30.0
5506,fea00d6f87d3f80808e9e8d1b501120a,184.0,296.0,395.0,0.371585,27.0
5507,fea00d6f87d3f80808e9e8d1b501120a,202.4,296.0,395.0,0.361788,24.0

#### **Redimensionamiento con grosor = 3mm**

Por último, redimensionemos los tipos de cajas con un grosor de 3mm.

In [60]:
for caja in cajas:
    caja.elegir_grosor(grosor_mm=3)
    
combinaciones_ordenadas_por_caja_3mm = {}

for caja in cajas:
    combinaciones_ordenadas = caja.redimensionamientos_posibles()
    combinaciones_ordenadas_por_caja_3mm[caja] = combinaciones_ordenadas

In [61]:
data = []

for caja, combinaciones in combinaciones_ordenadas_por_caja_3mm.items():
    for combinacion in combinaciones:
        data.append({
            'caja_id': caja.caja_id,
            'alto': combinacion['alto'],
            'ancho': combinacion['ancho'],
            'largo': combinacion['largo'],
            'utilizacion': combinacion['utilizacion_pallet'],
            'cantidad_cajas_pallet': combinacion['cantidad_cajas_pallet']
        })

df_todas_combinaciones_3mm = pd.DataFrame(data)
df_todas_combinaciones_3mm.to_csv('Redimensionamientos/redimensionamientos_3mm.csv', index=False)
df_todas_combinaciones_3mm

,caja_id,alto,ancho,largo,utilizacion,cantidad_cajas_pallet
0,02cf77de65b70dd77905e2e33d78478f,291.0,266.4,355.5,0.812399,48.0
1,02cf77de65b70dd77905e2e33d78478f,320.1,266.4,355.5,0.743331,40.0
2,02cf77de65b70dd77905e2e33d78478f,291.0,325.6,355.5,0.741717,36.0
3,02cf77de65b70dd77905e2e33d78478f,261.9,266.4,355.5,0.732800,48.0
4,02cf77de65b70dd77905e2e33d78478f,320.1,325.6,355.5,0.678658,30.0
...,...,...,...,...,...,...
5503,fea00d6f87d3f80808e9e8d1b501120a,202.4,296.0,434.5,0.385051,24.0
5504,fea00d6f87d3f80808e9e8d1b501120a,202.4,325.6,395.0,0.384879,24.0
5505,fea00d6f87d3f80808e9e8d1b501120a,165.6,296.0,395.0,0.360783,30.0
5506,fea00d6f87d3f80808e9e8d1b501120a,184.0,296.0,395.0,0.359522,27.0
5507,fea00d6f87d3f80808e9e8d1b501120a,202.4,296.0,395.0,0.350523,24.0