#### **FACTIBILIDAD DE LA SOLUCIÓN**

In [80]:
import pandas as pd 
import matplotlib.pyplot as plt
from importlib import reload
import copy

import Clases.asignacion as asignacion_module
reload(asignacion_module)
from Clases.asignacion import Asignacion

import Clases.caja as caja_module
reload(caja_module)
from Clases.caja import Caja

import Clases.producto as producto_module
reload(producto_module)
from Clases.producto import Producto

import Clases.solucion as solucion_module
reload(solucion_module)
from Clases.solucion import Solucion

catalogo_productos = pd.read_csv("Datos-finales/catalogo_productos.csv")
especificaciones_cajas = pd.read_csv("Datos-finales/especificaciones_cajas.csv")
operaciones_planta = pd.read_csv("Datos-finales/operaciones_planta.csv")
procurement_cajas = pd.read_csv("Datos-finales/procurement_cajas.csv")

cajas_redimensionadas_5mm = pd.read_csv("Redimensionamientos/redimensionamientos_5mm.csv")
cajas_redimensionadas_4pmm = pd.read_csv("Redimensionamientos/redimensionamientos_4.5mm.csv")
cajas_redimensionadas_3mm = pd.read_csv("Redimensionamientos/redimensionamientos_3mm.csv")

Guardamos primero los tipos de cajas y los productos en listas de python.

In [81]:
cajas = {
    row["caja_tipo_id"]: Caja(
        caja_id=row["caja_tipo_id"],
        dim_interior_ancho=row["caja_interior_ancho"],
        dim_interior_largo=row["caja_interior_largo"],
        dim_interior_alto=row["caja_interior_alto"]
    )
    for _, row in especificaciones_cajas.iterrows()
}

In [82]:
prod_op_merge = catalogo_productos.merge(operaciones_planta, on="codigo_producto")

productos = {
    row["codigo_producto"]: Producto(
        codigo_producto = row['codigo_producto'],
        cantidad_paquetes = row['cantidad_paquetes'],
        peso_paquete = row['peso_neto_paquete'],
        demanda_buenos_aires = row['volumen_producto_planta_buenos_aires'],
        demanda_curitiba = row['volumen_producto_planta_curitiba'],
        demanda_santiago = row['volumen_producto_planta_santiago'],
        demanda_monterrey = row['volumen_producto_planta_monterrey'],
        demanda_bakersfield = row['volumen_producto_planta_bakersfield'],
        dim_producto_ancho = row['dim_producto_ancho'], 
        dim_producto_largo = row['dim_producto_largo'],
        dim_producto_alto = row['dim_producto_alto']
    )
    for _, row in prod_op_merge.iterrows()
}

#### **Factibilidad con grosor = 5mm**

La idea sería ver cuántos tipos de cajas se pueden asignar por producto, considerando las restricciones de dimensión interna, headspace y resistencia a comprensión. Cada chequeo se verifica dentro de la class Asignacion.

Empecemos viendo la factiblidad con un tamaño de grosor de 5mm, importando antes las cajas redimensionadas.

In [83]:
cajas_5mm = cajas.copy()

for caja_id, caja in cajas_5mm.items(): 
    caja.elegir_grosor(5)

redimensiones_por_caja_5mm = {}

# Importamos las redimensiones posibles
for caja_id, caja in cajas_5mm.items():
    redimensiones_por_caja_5mm[caja_id] = []
    # Buscamos todas las combinaciones de redimensionamiento del tipo de caja
    combinaciones_caja = cajas_redimensionadas_5mm[cajas_redimensionadas_5mm['caja_id'] == caja_id]
    
    for _, row in combinaciones_caja.iterrows():
        redimensiones_por_caja_5mm[caja_id].append({
            'alto': row['alto'],
            'ancho': row['ancho'],
            'largo': row['largo'],
            'utilizacion_pallet': row['utilizacion'],
            'cantidad_cajas_pallet': row['cantidad_cajas_pallet']
        })
        
        # Ordenamos según la utilizacion de pallet de mayor a menor
        redimensiones_por_caja_5mm[caja_id] = sorted(
            redimensiones_por_caja_5mm[caja_id],
            key=lambda x: x['utilizacion_pallet'],
            reverse=True
        )

In [84]:
redimensiones_cajas_factibles_5mm = {}

for codigo, producto in productos.items():
    redimensiones_asignables = {}
    
    for caja_id, caja in cajas_5mm.items():
        redimensiones_validas_caja = []
        # Iteramos sobre cada combinación posible de redimensionamiento
        for combinacion in redimensiones_por_caja_5mm[caja_id]:
            caja_redimensionada = copy.deepcopy(caja)
            caja_redimensionada.redimensionar(combinacion['alto'], combinacion['ancho'], combinacion['largo'])
            
            # Chequeo factibilidad de la asignacion
            asignacion = Asignacion(producto, caja_redimensionada)
            if asignacion.es_asignacion_valida() and caja_redimensionada.utilizacion_pallet() >= 0.6:
                redimensiones_validas_caja.append(combinacion)
        
        if len(redimensiones_validas_caja) != 0:
            redimensiones_asignables[caja_id] = redimensiones_validas_caja
    
    redimensiones_cajas_factibles_5mm[codigo] = redimensiones_asignables

In [85]:
df_factibilidad_5mm = pd.DataFrame([
    {
        'codigo_producto': codigo_producto,
        'cantidad_cajas_asignables': len(cajas_asign),
    }
    for codigo_producto, cajas_asign in redimensiones_cajas_factibles_5mm.items()
])

df_factibilidad_5mm = df_factibilidad_5mm.sort_values('cantidad_cajas_asignables', ascending=False)
df_factibilidad_5mm

    codigo_producto  cantidad_cajas_asignables
302          BR0300                        107
247          BR0245                        105
304          BR0302                        105
90           BR0091                        100
341          BR0337                        100
..              ...                        ...
257          BR0255                          8
124          BR0124                          4
122          BR0122                          4
44           BR0045                          1
57           BR0058                          1

[427 rows x 2 columns]

In [86]:
conteo_redimensiones = {}

for codigo_producto, cajas_asignables in redimensiones_cajas_factibles_5mm.items():
    for caja_id, redimensiones in cajas_asignables.items():
        # Si la caja no existe, crearla
        if caja_id not in conteo_redimensiones:
            conteo_redimensiones[caja_id] = {}
        
        for combinacion in redimensiones:
            clave_redim = (
                combinacion['alto'],
                combinacion['ancho'],
                combinacion['largo'],
                combinacion['utilizacion_pallet'],
                combinacion['cantidad_cajas_pallet']
            )
            
            # Si la clave no existe, inicializarla en 0
            if clave_redim not in conteo_redimensiones[caja_id]:
                conteo_redimensiones[caja_id][clave_redim] = 0
            
            # Incrementar
            conteo_redimensiones[caja_id][clave_redim] += 1

In [88]:
data = []

for caja_id, redimensiones in conteo_redimensiones.items():
    for (alto, ancho, largo, utilizacion, cajas_pallet), cantidad in redimensiones.items():
        data.append({
            'caja_id': caja_id,
            'alto': alto,
            'ancho': ancho,
            'largo': largo,
            'utilizacion_pallet': utilizacion,
            'cantidad_cajas_pallet': cajas_pallet,
            'cantidad_productos': cantidad
        })

df_conteo = pd.DataFrame(data)

# Ordenar por cantidad de productos (de mayor a menor)
df_conteo = df_conteo.sort_values(['caja_id', 'utilizacion_pallet'], ascending=[True, False])
df_conteo

,caja_id,alto,ancho,largo,utilizacion_pallet,cantidad_cajas_pallet,cantidad_productos
7,02cf77de65b70dd77905e2e33d78478f,320.1,266.4,355.5,0.771946,40.0,5
3,02cf77de65b70dd77905e2e33d78478f,261.9,266.4,355.5,0.763013,48.0,20
5,02cf77de65b70dd77905e2e33d78478f,291.0,266.4,355.5,0.703895,40.0,10
1,02cf77de65b70dd77905e2e33d78478f,320.1,325.6,355.5,0.702963,30.0,6
4,02cf77de65b70dd77905e2e33d78478f,261.9,325.6,355.5,0.694828,36.0,13
...,...,...,...,...,...,...,...
1966,fea00d6f87d3f80808e9e8d1b501120a,184.0,325.6,355.5,0.743637,54.0,7
1967,fea00d6f87d3f80808e9e8d1b501120a,202.4,325.6,355.5,0.723705,48.0,4
1970,fea00d6f87d3f80808e9e8d1b501120a,165.6,296.0,355.5,0.681932,60.0,1
1965,fea00d6f87d3f80808e9e8d1b501120a,184.0,296.0,355.5,0.678048,54.0,17
1962,fea00d6f87d3f80808e9e8d1b501120a,202.4,296.0,355.5,0.659874,48.0,12